/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.unisa.project_se_group12;

import java.util.Iterator;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author PC MSI
 */
public class GUI extends javax.swing.JFrame {

    StackManage stack;
    Variables variables;
    
    public GUI() {
        initComponents();
        stack = new StackManage();
        variables = new Variables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean check(String real, String im){
        if (real.isEmpty() && im.isEmpty()){
            return false;
        }
        else if(real.isEmpty() && !(im.isEmpty())){
            real = "0";
        }
        else if (!(real.isEmpty()) && im.isEmpty()){
            im = "0";
        }
        try{
            Double.class.isInstance(Double.parseDouble(real));
            Double.class.isInstance(Double.parseDouble(im));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Not supported charcters","ERROR",JOptionPane.ERROR_MESSAGE);
            RealPart.setText("");
            ImPart.setText("");
            return false;
        }
        return true; 
    }
    
    public boolean check2Numbers(){
        if(stack.size()<=1){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
            return false;
        }else
            return true;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RealPart = new javax.swing.JTextField();
        ImPart = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Result = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        EnterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DiffButton = new javax.swing.JButton();
        PerButton = new javax.swing.JButton();
        DivButton = new javax.swing.JButton();
        InvertButton = new javax.swing.JButton();
        RadButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StackArea = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();
        dropButton = new javax.swing.JButton();
        dupButton = new javax.swing.JButton();
        overButton = new javax.swing.JButton();
        swapButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        varList = new javax.swing.JComboBox<>();
        varMinButton = new javax.swing.JButton();
        varAddButton = new javax.swing.JButton();
        varMajButton = new javax.swing.JButton();
        varSubButton = new javax.swing.JButton();
        variablesFields = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Real");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imaginary");

        RealPart.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        RealPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealPartActionPerformed(evt);
            }
        });
        RealPart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedReal(evt);
            }
        });

        ImPart.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        ImPart.setMaximumSize(new java.awt.Dimension(214, 2147483647));
        ImPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImPartActionPerformed(evt);
            }
        });
        ImPart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressedIM(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("+");

        Result.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        AddButton.setForeground(new java.awt.Color(0, 153, 153));
        AddButton.setText("+");
        AddButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        EnterButton.setBackground(new java.awt.Color(255, 255, 255));
        EnterButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        EnterButton.setForeground(new java.awt.Color(0, 153, 153));
        EnterButton.setText("ENTER");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("j");

        DiffButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        DiffButton.setForeground(new java.awt.Color(0, 153, 153));
        DiffButton.setText("-");
        DiffButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DiffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiffButtonActionPerformed(evt);
            }
        });

        PerButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        PerButton.setForeground(new java.awt.Color(0, 153, 153));
        PerButton.setText("x");
        PerButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerButtonActionPerformed(evt);
            }
        });

        DivButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        DivButton.setForeground(new java.awt.Color(0, 153, 153));
        DivButton.setText("÷");
        DivButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DivButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivButtonActionPerformed(evt);
            }
        });

        InvertButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        InvertButton.setForeground(new java.awt.Color(0, 153, 153));
        InvertButton.setText("Invert sign");
        InvertButton.setActionCommand("-x");
        InvertButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvertButtonActionPerformed(evt);
            }
        });

        RadButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        RadButton.setForeground(new java.awt.Color(0, 153, 153));
        RadButton.setText("√");
        RadButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STACK");

        StackArea.setColumns(20);
        StackArea.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        StackArea.setRows(5);
        jScrollPane1.setViewportView(StackArea);

        clearButton.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 153, 153));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        dropButton.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        dropButton.setForeground(new java.awt.Color(0, 153, 153));
        dropButton.setText("DROP");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        dupButton.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        dupButton.setForeground(new java.awt.Color(0, 153, 153));
        dupButton.setText("DUP");
        dupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupButtonActionPerformed(evt);
            }
        });

        overButton.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        overButton.setForeground(new java.awt.Color(0, 153, 153));
        overButton.setText("OVER");
        overButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overButtonActionPerformed(evt);
            }
        });

        swapButton.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        swapButton.setForeground(new java.awt.Color(0, 153, 153));
        swapButton.setText("SWAP");
        swapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OUTPUT");

        varList.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        varList.setForeground(new java.awt.Color(0, 153, 153));
        varList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "y", "x", "z" }));
        varList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varListActionPerformed(evt);
            }
        });

        varMinButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        varMinButton.setForeground(new java.awt.Color(0, 153, 153));
        varMinButton.setText("<\"x\"");
        varMinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varMinButtonActionPerformed(evt);
            }
        });

        varAddButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        varAddButton.setForeground(new java.awt.Color(0, 153, 153));
        varAddButton.setText("+\"x\"");
        varAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varAddButtonActionPerformed(evt);
            }
        });

        varMajButton.setBackground(new java.awt.Color(255, 255, 255));
        varMajButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        varMajButton.setForeground(new java.awt.Color(0, 153, 153));
        varMajButton.setText(">\"x\"");
        varMajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varMajButtonActionPerformed(evt);
            }
        });

        varSubButton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        varSubButton.setForeground(new java.awt.Color(0, 153, 153));
        varSubButton.setText("-\"x\"");
        varSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varSubButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DiffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(RadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DivButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(InvertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(RealPart, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ImPart, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(EnterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(varMajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varMinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varSubButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(varList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(variablesFields, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(overButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(swapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(14, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(229, 229, 229))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(dropButton)
                        .addGap(18, 18, 18)
                        .addComponent(dupButton)
                        .addGap(18, 18, 18)
                        .addComponent(swapButton)
                        .addGap(18, 18, 18)
                        .addComponent(overButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ImPart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(EnterButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RealPart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(54, 54, 54)
                        .addComponent(varMajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(AddButton)
                                                .addComponent(DiffButton))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(RadButton)
                                                .addComponent(varMinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PerButton)
                                            .addComponent(varAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(InvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DivButton))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varSubButton))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(varList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(variablesFields, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void swapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapButtonActionPerformed
        if(stack.size()<=1){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            stack.swap();
            StackArea.setText(printStack());
        }
    }//GEN-LAST:event_swapButtonActionPerformed

    private void overButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overButtonActionPerformed
        if(stack.size()<=1){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            stack.over();
            StackArea.setText(printStack());
        }
    }//GEN-LAST:event_overButtonActionPerformed

    private void dupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            stack.dupLastElement();
            StackArea.setText(printStack());
        }
    }//GEN-LAST:event_dupButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            stack.popFromStack();
            StackArea.setText(printStack());
        }
    }//GEN-LAST:event_dropButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        stack.clearStack();
        StackArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void RadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else {
            ComplexNumbers num1 = stack.popFromStack();
            ComplexNumbers res = new ComplexOperations().squareRoot(num1);
            stack.pushtoStack(res);
            StackArea.setText(printStack());
            Result.setText(res.toString());
        }
    }//GEN-LAST:event_RadButtonActionPerformed

    private void InvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvertButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            ComplexNumbers num1 = stack.popFromStack();
            ComplexNumbers res = new ComplexOperations().invertSign(num1);
            stack.pushtoStack(res);
            StackArea.setText(printStack());
            Result.setText(res.toString());
        }
    }//GEN-LAST:event_InvertButtonActionPerformed

    private void DivButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivButtonActionPerformed
        if(check2Numbers()){
            ComplexNumbers num2 = stack.popFromStack();
            ComplexNumbers num1 = stack.popFromStack();
            if(num1.getReal()==0){
                JOptionPane.showMessageDialog(this, "Enter a non zero divider","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                ComplexNumbers res = new ComplexOperations().divide(num1, num2);
                stack.pushtoStack(res);
                StackArea.setText(printStack());
                Result.setText(res.toString());
            }
        }
    }//GEN-LAST:event_DivButtonActionPerformed

    private void PerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerButtonActionPerformed
        if(check2Numbers()){
            ComplexNumbers num1 = stack.popFromStack();
            ComplexNumbers num2 = stack.popFromStack();
            ComplexNumbers res = new ComplexOperations().multiply(num1, num2);
            stack.pushtoStack(res);
            StackArea.setText(printStack());
            Result.setText(res.toString());
        }
    }//GEN-LAST:event_PerButtonActionPerformed

    private void DiffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiffButtonActionPerformed
        if(check2Numbers()){
            ComplexNumbers num2 = stack.popFromStack();
            ComplexNumbers num1 = stack.popFromStack();
            ComplexNumbers res = new ComplexOperations().subtract(num1, num2);
            stack.pushtoStack(res);
            StackArea.setText(printStack());
            Result.setText(res.toString());
        }
    }//GEN-LAST:event_DiffButtonActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        String real = RealPart.getText();
        String im = ImPart.getText();
        if(check(real, im)){
            stack.addIntoStack(real, im);
            StackArea.setText(printStack());
            RealPart.setText("");
            ImPart.setText("");
        }else
        JOptionPane.showMessageDialog(this, "Enter a valid Number","ERROR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if(check2Numbers()){
            ComplexNumbers num1 = stack.popFromStack();
            ComplexNumbers num2 = stack.popFromStack();
            ComplexNumbers res = new ComplexOperations().add(num1, num2);
            stack.pushtoStack(res);
            StackArea.setText(printStack());
            Result.setText(res.toString());
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void keyPressedIM(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressedIM
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            String real = RealPart.getText();
            String im = ImPart.getText();
            if(check(real, im)){
                stack.addIntoStack(real, im);
                StackArea.setText(printStack());
                RealPart.setText("");
                ImPart.setText("");
            }
        }
    }//GEN-LAST:event_keyPressedIM

    private void ImPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImPartActionPerformed

    }//GEN-LAST:event_ImPartActionPerformed

    private void keyPressedReal(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressedReal
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            String real = RealPart.getText();
            String im = ImPart.getText();
            if(check(real, im)){
                stack.addIntoStack(real, im);
                StackArea.setText(printStack());
                RealPart.setText("");
                ImPart.setText("");
            }
        }
    }//GEN-LAST:event_keyPressedReal

    private void RealPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealPartActionPerformed

    }//GEN-LAST:event_RealPartActionPerformed

    private void varMajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varMajButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            variables.pushIntoVariable(varList.getSelectedItem().toString(), stack);
            variablesFields.setText(variables.getMap().get(varList.getSelectedItem().toString()).toString());
        }
    }//GEN-LAST:event_varMajButtonActionPerformed

    private void varListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varListActionPerformed
        if(variables.getMap().get(varList.getSelectedItem().toString())== null){
            variablesFields.setText("");
        }else{
            variablesFields.setText(variables.getMap().get(varList.getSelectedItem().toString()).toString());
        }
    }//GEN-LAST:event_varListActionPerformed

    private void varAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varAddButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else if(variables.getMap().get(varList.getSelectedItem().toString())== null){
            JOptionPane.showMessageDialog(this, "Variable not initialized","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            variables.addWithStack(varList.getSelectedItem().toString(), stack);
            variablesFields.setText(variables.getMap().get(varList.getSelectedItem().toString()).toString());
        }
    }//GEN-LAST:event_varAddButtonActionPerformed

    private void varMinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varMinButtonActionPerformed
         if(variables.getMap().get(varList.getSelectedItem().toString())== null){
            JOptionPane.showMessageDialog(this, "Variable not initialized","ERROR",JOptionPane.ERROR_MESSAGE);
         }else {
            variables.pushIntoStack(varList.getSelectedItem().toString(), stack);
            StackArea.setText(printStack());
         }
    }//GEN-LAST:event_varMinButtonActionPerformed

    private void varSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varSubButtonActionPerformed
        if(stack.size()<=0){
            JOptionPane.showMessageDialog(this, "Not enough numbers, insert another number!","ERROR",JOptionPane.ERROR_MESSAGE);
        }else if(variables.getMap().get(varList.getSelectedItem().toString())== null){
            JOptionPane.showMessageDialog(this, "Variable not initialized","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            variables.subWithStack(varList.getSelectedItem().toString(), stack);
            variablesFields.setText(variables.getMap().get(varList.getSelectedItem().toString()).toString());
        }
    }//GEN-LAST:event_varSubButtonActionPerformed

    private String printStack(){
        String str="";
        Iterator<ComplexNumbers> iter = stack.iteratorStack();
        
        while(iter.hasNext()){
            str = str + iter.next().toString() ;
        }
        return str;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DiffButton;
    private javax.swing.JButton DivButton;
    private javax.swing.JButton EnterButton;
    private javax.swing.JTextField ImPart;
    private javax.swing.JButton InvertButton;
    private javax.swing.JButton PerButton;
    private javax.swing.JButton RadButton;
    private javax.swing.JTextField RealPart;
    private javax.swing.JTextField Result;
    private javax.swing.JTextArea StackArea;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton dropButton;
    private javax.swing.JButton dupButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton overButton;
    private javax.swing.JButton swapButton;
    private javax.swing.JButton varAddButton;
    private javax.swing.JComboBox<String> varList;
    private javax.swing.JButton varMajButton;
    private javax.swing.JButton varMinButton;
    private javax.swing.JButton varSubButton;
    private javax.swing.JTextField variablesFields;
    // End of variables declaration//GEN-END:variables
}
